In [1]:
! pip install numpy

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np

## Use numpy predifined functions

# Arrays

###  when you put an integer, a Boolean, and a string in the same Numpy array using the array()  all array element are converted to string

In [3]:
a = np.array([[1,2,3],[4,5,6]]) 

In [4]:
b=np.array([[1,True,"hi"]]) # only in the case where they are M5ALTIN sinon kol we7ed yo93od bil type mte3ou 

In [5]:
type(b[0,0])

numpy.str_

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print (a.shape)

(2, 3)


In [8]:
a[0,1] # first row second column

2

In [9]:
a[0]=5

In [10]:
a

array([[5, 5, 5],
       [4, 5, 6]])

# -------------------------------------COOL-------------------------------

# eye

In [11]:
d=np.eye(2)

In [12]:
d

array([[1., 0.],
       [0., 1.]])

# random

In [13]:
r=np.random.randint(20, size=(4, 3))

In [14]:
r

array([[15, 11,  0],
       [10,  6, 10],
       [ 9,  4,  6],
       [ 7, 10,  9]])

# Zero

In [15]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# boolean indexing

In [16]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [17]:
bool_idx = (a > 2)

In [18]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [19]:
a[bool_idx]

array([3, 4, 5, 6])

In [20]:
a[a>2]

array([3, 4, 5, 6])

# math functions

In [21]:
x = np.array([[1,49],[9,4]])
y = np.array([[5,6],[7,8]])

In [22]:
x+y # condition on the shape !!!! math stuff

array([[ 6, 55],
       [16, 12]])

In [23]:
np.sqrt(x)

array([[1., 7.],
       [3., 2.]])

In [24]:
np.add(x,y)

array([[ 6, 55],
       [16, 12]])

In [25]:
np.dot(x,y) #returns matrix product

array([[348, 398],
       [ 73,  86]])

In [26]:
np.multiply(x,y)

array([[  5, 294],
       [ 63,  32]])

In [27]:
x.sum()# returns the sum of all element in x

63

In [28]:
np.sum(x)

63

In [29]:
c=np.arange(10)

In [30]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
s = slice(2,7,2) 

In [32]:
s

slice(2, 7, 2)

In [33]:
a[s]

array([[5, 6]])